# Generated by Django 3.0.3 on 2020-04-19 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracksvc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CheckEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default=datetime.datetime.now)),
                ('notes', models.CharField(max_length=200)),
                ('present', models.BooleanField(default=False)),
                ('loaded', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('firearm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracksvc.Firearm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracksvc.User')),
            ],
            options={
                'ordering': ['when'],
            },
        ),
    ]
