# Generated by Django 3.0.3 on 2020-04-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksvc', '0002_checkevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkevent',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
